### ISSUE TITLE
"Ran out of packets?!" when seeking

### ISSUE THREAD

**Issue by waltdestler** [NVorbis/NVorbis#19]
The new 0.10.3 release appears to have a bug that causes an `InvalidDataException` to be thrown with the message "Ran out of packets?!" when seeking/setting the sample position. This appears to be a regression in 0.10.3; it did not happen for me in 0.10.2.

Here is a small sample program that easily reproduces the issue for me:

```
using NVorbis;

namespace NVorbisTest
{
    class Program
    {
        static void Main()
        {
            VorbisReader reader = new("test.ogg");
            while (reader.SamplePosition < reader.TotalSamples)
                reader.SamplePosition += reader.Channels;
        }
    }
}
```

I have been able to reproduce this easily with every ogg file I've tried, but just in case here is a [test.ogg](https://github.com/NVorbis/NVorbis/files/6411889/test.ogg.zip) file that I know reproduces this issue consistently for me.

For convenience, here is the stack trace:

```
System.IO.InvalidDataException: Ran out of packets?!
   at NVorbis.Ogg.PacketProvider.FindPacket(Int32 pageIndex, Int64& granulePos, GetPacketGranuleCount getPacketGranuleCount, Boolean isRecursed)
   at NVorbis.Ogg.PacketProvider.SeekTo(Int64 granulePos, Int32 preRoll, GetPacketGranuleCount getPacketGranuleCount)
   at NVorbis.StreamDecoder.SeekTo(Int64 samplePosition, SeekOrigin seekOrigin)
   at NVorbis.StreamDecoder.set_SamplePosition(Int64 value)
   at NVorbis.VorbisReader.set_SamplePosition(Int64 value)
   at NVorbisTest.Program.Main() in C:\Users\walt\Desktop\NVorbisTest\Program.cs:line 11
```

**Comment by ioctlLR** [comment]
OK, ya gotta admit that's a pathological use case... 😉 

The v0.10.3 seek algorithm tested out as consistent in seeking to the correct sample for me (which had previously been a problem), so we just need to figure out why it's failing this way.  Theoretically that error means it either looked at the wrong page, it counted samples wrong, or the file is corrupt.  Given you can repro it readily and decoding counts samples correctly, I expect it's probably not finding the correct page.  Good test!

If necessary I can probably side-step it by having StreamDecoder.SeekTo(...) try to handle the seek when the new position is between the start of the current packet and 1/4 of the way into the smallest possible next packet (since we can make guarantees about that range) without having to seek in the packet provider...  Probably a useful optimization anyway so I might do that as part of this fix and maybe put in a feature flag to turn it off.

**Comment by waltdestler** [comment]
Haha yeah, this "pathological" code was just the simplest 100% repro I could come up with after encountering the bug in my *actual* real-world code. (A game with multiple overlapping ogg tracks that all need to be kept in perfect sync even if they're not actually playing, so the tracks that aren't playing I seek ahead instead of actually decoding to save CPU cycles. In this case they're seeking thousands of samples ahead at a time, not just 1-2, but 1-2 is what repros 100%.)

**Comment by waltdestler** [comment]
Hey @ioctlLR, I have been looking into this bug and I *think* I have identified two separate bugs that can cause this exception to be thrown. The first bug I believe I know exactly why it happens and the fix is very straightforward. The second bug I don't understand why it happens and I don't really understand either the Ogg Vorbis format or NVorbis itself well enough to figure out on my own. If you have time, I would greatly appreciate you sanity-checking my understand/fix of the first bug and looking into the second bug.

----

**Bug 1**

My understanding of Ogg Vorbis (and I'm sure you know much more than I do, so please correct me if I'm wrong), is that the granule position of each page is *the number of samples up to and including all the samples in that page*, meaning that the granule position of a page is actually *the index of the first sample of the next page* (I'm assuming samples are zero-indexed).

Assuming my understanding is correct, then there are at least three places in the code where essentially an "off by one" bug occurs, where if you happen to query for the very first sample of a page, the code will erroneously return the index of the *previous* page instead. The places in the code where I believe this happens are:

1. In `StreamPageReader.FindPage()` line 151, `pageIndex = lastPageIndex;` should be `pageIndex = lastPageIndex + 1;`
2. In `StreamPageReader.FindPageForward()` line 164, `while (pageGranulePos < granulePos)` should be `while (pageGranulePos <= granulePos)`
3. In `StreamPageReader.FindPageBisection()` line 245, `return index;` should be `return index + 1;`

These are the places I've found where this is an issue, and fixing them seems to solve all of the "very first sample of a page" bugs I've run into, but there may be more places I haven't discovered yet in my tests. I would appreciate if you could sanity-check my understanding and fixes.

----

**Bug 2**

While fixing the above bug solves *most* of the seeking issues I've encountered, I've still found certain sample positions (not on page boundaries) that can cause the "Ran out of packets" error, depending on the file being read.

Although I've been able to find such sample positions in every ogg vorbis file I've tested (5 different files from multiple sources, so I don't believe this is an issue with the files themselves), the easiest way to repro is to simply load the [test.ogg](https://github.com/NVorbis/NVorbis/files/6411889/test.ogg.zip) from my original post and seek directly to position 523000:

````
using NVorbis;

namespace NVorbisTest
{
    class Program
    {
        static void Main()
        {
            VorbisReader reader = new("test.ogg");
            reader.SamplePosition = 523000;
        }
    }
}
````

The bug here, to the extent that I understand it, is that the correct page IS being calculated (`granualPos` is between `startGP` and `endGP`), but the actual number of granules from all the packets isn't adding up high enough to cover the whole range of the page. *Why* this is happening I do not understand and I don't feel like I understand either NVorbis or Ogg Vorbis well enough to effectively debug. Maybe you are able to provide some insight here? (I'm assuming that either the number of packets is being miscalculated, or the size of some/all of the individual packets are being miscalculated.)

**Comment by ioctlLR** [comment]
Well, I had to go check the spec to be sure, but your first bugfix is correct.  I'll take a PR for that. :)

Your impression on the other item is probably right, but I haven't figured out precisely _why_ it's miscalculating.  I'll try to look at it in the morning.

**Comment by ioctlLR** [comment]
@waltdestler, call me crazy but that file doesn't even have 523,000 samples!  I even double-checked it in Audacity...  269,188 total samples.

**Comment by waltdestler** [comment]
Yeah sorry, looks like somehow the wrong test.ogg was getting copied to my project's output folder. Will need some time to find another repro.

**Comment by waltdestler** [comment]
Okay, sorry for the mixup earlier and for the delay getting a good repro. I wanted to make absolutely sure that it wasn't an issue on my end or with my particular ogg files. (I have since found a number of sample ogg files online that have the same issue, so at this point I'm pretty confident that it is indeed a bug with NVorbis as I originally described.)

To repro, open this file and seek to sample 86400: [file_example_OOG_1MG.zip](https://github.com/NVorbis/NVorbis/files/7230331/file_example_OOG_1MG.zip)

```
VorbisReader reader = new("file_example_OOG_1MG.ogg");
reader.SamplePosition = 86400;
```

(In the process of testing, I also found another couple of exceptions while seeking, but they are different exceptions so I will open different issues for them.)

**Comment by ioctlLR** [comment]
Haha, no worries; I'm pretty sure I found it.  PacketProvider.FindPacket(...) line 126 should use >= rather than >.

**Comment by waltdestler** [comment]
Verified that PR #25 fixes seeking to sample 86400 in the above ogg file, but seeking to sample 86420 fails.

**Comment by ioctlLR** [comment]
Well...  I really hate to say this but I think the official Vorbis encoder used for that file has a bug.  Pages that end on a long packet that are followed by a short packet in the next page don't get counted correctly (for packet sizes of 2048 and 256, it under counts by 448 samples in the page's header).  NOT what I was expecting to find, but it's consistent.

I'm actually at a bit of a loss as to how to properly fix this...  Probably going to have to special-case the packet finding logic to handle it.  So much for separation of the container from the stream decoder...

Thoughts?

**Comment by waltdestler** [comment]
Wow, that is very strange! Strange enough that I have to wonder whether it's really a bug, or there's something else going on. I guess my instinct would be to contact someone who maintains libvorbis (I see they do have a [mailing list](http://lists.xiph.org/mailman/listinfo/vorbis)) and/or see how libvorbis handles this issue.

**Comment by waltdestler** [comment]
448 is an awfully suspicious number because, if I understand the spec correctly, that's the number of samples that go unused in a 2048 packet if it's followed by a 256 packet (2048/4-256/4=448). Is there maybe a misunderstanding between NVorbis and the official implementation about whether those extra samples should be counted in the pages? (This is way out of my area of expertise, so I apologize if this is something you've already checked. I literally just now learned about overlapping vorbis packets today.)

**Comment by ioctlLR** [comment]
https://xiph.org/vorbis/doc/framing.html is the spec that applies, specifically the section names "Absolute granule position".  Per that description, the encoder is wrong. :)

That's OK though.  I think I know how to address the problem in a generic way (funny how a night of good sleep will do that!).

**Comment by waltdestler** [comment]
Confirmed fixed!
