### ISSUE TITLE
IndexOutOfRangeException in PacketProvider.CreatePacket while seeking

### ISSUE THREAD

**Issue by waltdestler** [NVorbis/NVorbis#23]
To reproduce, open [Tromboon.ogg](https://github.com/NVorbis/NVorbis/files/7230350/Tromboon.zip) and seek to sample 23104:

```
VorbisReader reader = new("Tromboon.ogg");
reader.SamplePosition = 23104;
```

This throws a `IndexOutOfRangeException` in `PacketProvider.CreatePacket` (line 210; `_reader.GetPagePackets(pageIndex)` returns an array of length 17 but `packetIndex` is 23.)

I have been able to reproduce this with multiple unrelated ogg files.

**Comment by waltdestler** [comment]
Not fixed by PR #25, still repros as originally described. (Except `packetIndex` is now 22 instead of 23, still beyond the end of the array.)

**Comment by ioctlLR** [comment]
OK, this one will be fixed by the next push.  The logic didn't specifically account for the desired granule being the first one on the page and the continued packet logic completely blew it up.

**Comment by waltdestler** [comment]
Seeking to sample 23104 now seems to work, but I found another sample that throws: 23146

**Comment by ioctlLR** [comment]
One more time...  I'll fully test it after work before merging.

**Comment by waltdestler** [comment]
Confirmed fixed on my end. Everything appears to be working!
