### ISSUE TITLE
rollForward results in negative value on seeking, resulting in negative _prevPacketStart

### ISSUE THREAD

**Issue by Frooxius** [NVorbis/NVorbis#28]
Hello!

I've ran into a seeking issue with this .ogg file: [SGM_example.zip](https://github.com/NVorbis/NVorbis/files/7285897/SGM_example.zip)

Seek to position `678951`
```vorbRead.SamplePosition = 678951;```

If you then call `ReadSamples`, it will throw an IndexOutOfRange exception in ClippingCopyBuffer.

I've found that this is due to the `var pos = _packetProvider.SeekTo(samplePosition, 1, GetPacketGranules);` in StreamDecoder.cs returning position that's ahead of the samplePosition.

This results in rollForward being negative and _prevPacketStart negative as well, causing the IndexOutOfRange on next read. Unfortunately I'm not sure how to fix this myself, but I hope this helps!

**Comment by TechPizzaDev** [comment]
I have attempted to fix this in my fork.
[This commit](https://github.com/TechPizzaDev/VorbisPizza/commit/3e1e9486671dbc8c1c0b4ffbed548fba399c2f43) contains relevant changes, but I have changed many more things that may have contributed to fixing this seek bug.

**Comment by ioctlLR** [comment]
@Frooxius, @TechPizzaDev, please try again with v0.10.5.
