### ISSUE TITLE
Documentation is ambiguous

### ISSUE THREAD

**Issue by AllFatherGray** [NVorbis/NVorbis#30]
I've been trying to speak to someone in the chat on Element to get guidance on merging ogg files. 

The example in the Readme doesn't show much. 
Am I meant to place the read buffer into the stream? If so, does reading the ogg file have a header to account for?
I see a comment for "// 200MS". Is the read buffer meant to be that way for all samples?

**Comment by ioctlLR** [comment]
@AllFatherGray do you still need assistance?  I know it's been quite some time...
