### ISSUE TITLE
Build on .NET 6

### ISSUE THREAD

**Issue by s5bug** [NVorbis/NVorbis#31]
NVorbis builds just fine if you add `net6.0` to its `TargetFrameworks`. Is there any reason this shouldn't be done?

A project that I'm trying to get to build entirely on net6 as a self-challenge depends on NAudio.Vorbis. NAudio recently got net6 builds in 2.1.0-beta.1, and NAudio.Vorbis builds fine in net6 on those as well. I'm not skilled enough at .NET to understand why NAudio.Vorbis builds on net6 without NVorbis building on net6, but my gut tells me here's the best place to ask.

**Comment by ioctlLR** [comment]
The library is built for netstandard2.0, which is fully compatible with .NET Core 3.0 and newer (which includes .NET 5/6/7).
