### ISSUE TITLE
Dead loop in StreamDecoder.Read()

### ISSUE THREAD

**Issue by fantasyz** [NVorbis/NVorbis#32]
```
// try to fill the buffer; drain the last buffer if EOS, resync, bad packet, or parameter change
while (idx < tgt)
{
    // if we don't have any more valid data in the current packet, read in the next packet
    if (_prevPacketStart == _prevPacketEnd)
    {
        if (_eosFound)
        {
            _nextPacketBuf = null;
            _prevPacketBuf = null;

            // no more samples, so just return
            break;
        }

        if (!ReadNextPacket((idx - offset) / _channels, out var samplePosition))
        {
            // drain the current packet (the windowing will fade it out)
            _prevPacketEnd = _prevPacketStop;
        }

        // if we need to pick up a position, and the packet had one, apply the position now
        if (samplePosition.HasValue && !_hasPosition)
        {
            _hasPosition = true;
            _currentPosition = samplePosition.Value - (_prevPacketEnd - _prevPacketStart) - (idx - offset) / _channels;
        }
    }

    // we read out the valid samples from the previous packet
    var copyLen = Math.Min((tgt - idx) / _channels, _prevPacketEnd - _prevPacketStart);
    if (copyLen > 0)
    {
        if (ClipSamples)
        {
            idx += ClippingCopyBuffer(buffer, idx, copyLen);
        }
        else
        {
            idx += CopyBuffer(buffer, idx, copyLen);
        }
    }
}
```

Not happen all the time, but when it happen, inside this while loop, while _eosFound is true, but code doesn't enter this if bracket. I don't know how but the _prevPacketEnd is small than _prevPacketStart causing copyLen to be negative value. The loop doesn't exit at all. 

I temporarily added an if to check if copyLen is negative and return early to break the loop. No sure if the issue is caused by the ogg file but I cannot provide it due to copy right issue.

**Comment by ioctlLR** [comment]
I'm gonna need an OGG file to repro this with.  If necessary, we can arrange to transfer it privately.

**Comment by ioctlLR** [comment]
@fantasyz please try again with v0.10.5.

**Comment by TechPizzaDev** [comment]
While https://github.com/NVorbis/NVorbis/pull/34 seems to be a good change, I still have problems with the actual decoding.
The `issue6test.ogg` file in this repo decodes incorrectly after a seek at position `16961`. I am not sure how to properly fix this.

**Comment by TechPizzaDev** [comment]
@ioctlLR Are you planning on looking into this further? I could open a new issue.
If you do not plan on looking into this, I would like to rewrite a portion of the page tracking code in my own fork to attempt to fix this.
