### ISSUE TITLE
Infinite loop on fast seek

### ISSUE THREAD

**Issue by tw-easy** [NVorbis/NVorbis#4]
I was stressing out my player NAudio-NVorbis based and I also upgrade NVorbis at the latest version but when I perform lots of seeks during playback it causes a deadlock because of the infinite loop as shown in the screenshot
![err2](https://user-images.githubusercontent.com/3462893/78662881-7f739280-78d1-11ea-9154-1f9455bd3268.jpg)

Assuming that:
granulePos = 79062591
highGranulePos = 79062592
low = 3
lowGranulePos = num1 = 0 
dist = num2 = 222

int index = low + (int)(dist * ((granulePos - lowGranulePos) / (float)(highGranulePos - lowGranulePos)));

then

index = 3 + (int)(222*((79062591 - 0) / (79062592 - 0))

should give 224 but at runtime 225 is calculated, casting to double instead float works fine 

int index = low + (int)(dist * ((granulePos - lowGranulePos) / (double)(highGranulePos - lowGranulePos)))

**Comment by ioctlLR** [comment]
Interesting!  Makes sense that we're losing precision there.  Lemme see about another release over the weekend, if that'll work for you.

**Comment by ioctlLR** [comment]
Fixed in v0.10.1
