### ISSUE TITLE
Need lots more tests

### ISSUE THREAD

**Issue by ericwood8** [NVorbis/NVorbis#9]
WHAT WORKS: Test App project can be set as the Startup project and it plays a sample OGG file.
PROBLEMS: 1) Usage instructions are not even a unit test. 2) The current usage instructions require you to ReadSamples with 4 parameters but current implementation only has 3 parameters. 3) I am not sure that the current usage instructions even plays the sound.  It seems to read the file but not actually play anything.  4) The current TestApp project is not a even test project.  5) The only test in the current TestApp project requires a external dependency on a 3rd party application called NAudio .  (If you want to show how to utilize NAudio integration, then you should build another test app just for it and take the dependency there.)  6) There is no active test for the ForwardOnlyStream unit that was provided in the TestApp.

**Comment by ioctlLR** [comment]
Soooo... You're volunteering to add the unit tests?  I'd love to, but I work on this as a side hobby type project and just haven't had time to do so.  Please feel free to start working on it in a pull request.

**Comment by ioctlLR** [comment]
Closing in favor of #11.
